import type { Lead, Client, Task, Activity, RevenueDataPoint, LeadSourceDataPoint } from './types'

export const mockLeads: Lead[] = [
  {
    id: 'l1',
    name: 'Alexandra Chen',
    company: 'Vertex Systems',
    email: 'a.chen@vertexsystems.io',
    phone: '+1 (415) 823-4401',
    status: 'proposal',
    value: 24000,
    lastContact: '2026-04-15',
    source: 'LinkedIn',
    industry: 'Technology',
    notes: 'Interested in full branding + web redesign. Decision by end of Q2.',
  },
  {
    id: 'l2',
    name: 'Marcus Webb',
    company: 'Harvest Financial',
    email: 'm.webb@harvestfinancial.com',
    phone: '+1 (312) 774-9920',
    status: 'contacted',
    value: 15500,
    lastContact: '2026-04-17',
    source: 'Referral',
    industry: 'Finance',
    notes: 'Needs a landing page and SEO strategy.',
  },
  {
    id: 'l3',
    name: 'Priya Nair',
    company: 'NovaMed Health',
    email: 'priya.nair@novamed.health',
    phone: '+1 (650) 998-3310',
    status: 'won',
    value: 38000,
    lastContact: '2026-04-10',
    source: 'Cold Outreach',
    industry: 'Healthcare',
    notes: 'Signed contract for patient portal redesign.',
  },
  {
    id: 'l4',
    name: 'James Okafor',
    company: 'Drift Creative Studio',
    email: 'james@driftcreative.co',
    phone: '+1 (929) 445-2271',
    status: 'new',
    value: 9200,
    lastContact: '2026-04-18',
    source: 'Website',
    industry: 'Design',
    notes: 'Reached out via contact form. Wants logo + brand kit.',
  },
  {
    id: 'l5',
    name: 'Sofia Reyes',
    company: 'BluePeak Realty',
    email: 's.reyes@bluepeakrealty.com',
    phone: '+1 (213) 663-0981',
    status: 'lost',
    value: 12000,
    lastContact: '2026-04-01',
    source: 'LinkedIn',
    industry: 'Real Estate',
    notes: 'Went with a competitor. Follow up in 6 months.',
  },
  {
    id: 'l6',
    name: 'Daniel Park',
    company: 'Stackr Labs',
    email: 'd.park@stackrlabs.dev',
    phone: '+1 (408) 554-7732',
    status: 'proposal',
    value: 52000,
    lastContact: '2026-04-14',
    source: 'Conference',
    industry: 'Technology',
    notes: 'Needs full-stack SaaS MVP. Very promising.',
  },
  {
    id: 'l7',
    name: 'Amara Johnson',
    company: 'GreenLeaf Organics',
    email: 'amara@greenleaforganics.com',
    phone: '+1 (503) 820-1145',
    status: 'contacted',
    value: 6800,
    lastContact: '2026-04-16',
    source: 'Instagram',
    industry: 'Retail',
    notes: 'Small e-commerce site + branding.',
  },
  {
    id: 'l8',
    name: 'Ryan Kowalski',
    company: 'Meridian Consulting',
    email: 'ryan.k@meridianconsulting.biz',
    phone: '+1 (617) 390-4452',
    status: 'won',
    value: 29500,
    lastContact: '2026-04-08',
    source: 'Referral',
    industry: 'Consulting',
    notes: 'Ongoing retainer for UX/UI work.',
  },
  {
    id: 'l9',
    name: 'Isabelle Fontaine',
    company: 'Lumio Events',
    email: 'isabelle@lumioevents.fr',
    phone: '+33 6 12 34 56 78',
    status: 'new',
    value: 11000,
    lastContact: '2026-04-19',
    source: 'Dribbble',
    industry: 'Events',
    notes: 'Event microsite + invite design.',
  },
  {
    id: 'l10',
    name: 'Carlos Mendes',
    company: 'TerraForm Energy',
    email: 'c.mendes@terraformenergy.com',
    phone: '+1 (737) 221-5093',
    status: 'contacted',
    value: 18000,
    lastContact: '2026-04-12',
    source: 'Cold Outreach',
    industry: 'Energy',
    notes: 'Investor deck + website.',
  },
]

export const mockClients: Client[] = [
  {
    id: 'c1',
    name: 'Priya Nair',
    company: 'NovaMed Health',
    email: 'priya.nair@novamed.health',
    phone: '+1 (650) 998-3310',
    website: 'novamed.health',
    revenue: 38000,
    since: '2025-11-01',
    industry: 'Healthcare',
    location: 'San Francisco, CA',
    notes: 'Long-term client, very responsive. Prefers async communication over Slack.',
    avatarColor: '#0ea5e9',
  },
  {
    id: 'c2',
    name: 'Ryan Kowalski',
    company: 'Meridian Consulting',
    email: 'ryan.k@meridianconsulting.biz',
    phone: '+1 (617) 390-4452',
    website: 'meridianconsulting.biz',
    revenue: 29500,
    since: '2025-09-15',
    industry: 'Consulting',
    location: 'Boston, MA',
    notes: 'Monthly retainer arrangement. Reviews on the 1st of each month.',
    avatarColor: '#f59e0b',
  },
  {
    id: 'c3',
    name: 'Elena Vasquez',
    company: 'Orion Digital Media',
    email: 'elena@oriondigital.co',
    phone: '+1 (646) 887-3312',
    website: 'oriondigital.co',
    revenue: 21000,
    since: '2025-07-20',
    industry: 'Media',
    location: 'New York, NY',
    notes: 'Wants quarterly strategy reports alongside deliverables.',
    avatarColor: '#10b981',
  },
  {
    id: 'c4',
    name: 'Tom Blackwell',
    company: 'Atlas Ventures',
    email: 't.blackwell@atlasventures.vc',
    phone: '+1 (415) 230-9871',
    website: 'atlasventures.vc',
    revenue: 55000,
    since: '2024-12-01',
    industry: 'Finance',
    location: 'San Francisco, CA',
    notes: 'High-value client. Strict NDA. Always pays early.',
    avatarColor: '#6366f1',
  },
  {
    id: 'c5',
    name: 'Yuki Tanaka',
    company: 'Kibo Commerce',
    email: 'yuki@kibocommerce.jp',
    phone: '+81 90-1234-5678',
    website: 'kibocommerce.jp',
    revenue: 17500,
    since: '2026-01-10',
    industry: 'E-commerce',
    location: 'Tokyo, Japan',
    notes: 'New client. International invoicing required. 14-day payment terms.',
    avatarColor: '#ef4444',
  },
]

export const mockActivities: Activity[] = [
  { id: 'a1', type: 'call', description: 'Discovery call — discussed project scope and timeline expectations.', date: '2026-04-18', user: 'You' },
  { id: 'a2', type: 'email', description: 'Sent initial proposal draft with three service tier options.', date: '2026-04-16', user: 'You' },
  { id: 'a3', type: 'meeting', description: 'Video call — aligned on brand direction and confirmed budget range.', date: '2026-04-10', user: 'You' },
  { id: 'a4', type: 'proposal', description: 'Final proposal signed and returned. Project kick-off scheduled.', date: '2026-04-05', user: 'You' },
  { id: 'a5', type: 'note', description: 'Client prefers Figma for design reviews. Weekly check-ins every Friday.', date: '2026-03-28', user: 'You' },
  { id: 'a6', type: 'contract', description: 'Contract executed and first invoice sent ($9,500 deposit).', date: '2026-03-20', user: 'You' },
]

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Finalize proposal for Stackr Labs',
    description: 'Complete pricing breakdown and timeline for the SaaS MVP proposal.',
    priority: 'high',
    status: 'in_progress',
    dueDate: '2026-04-22',
    clientId: undefined,
    clientName: 'Stackr Labs',
    tags: ['proposal', 'design'],
  },
  {
    id: 't2',
    title: 'Send invoice #INV-041 to Atlas Ventures',
    description: 'Monthly retainer invoice for April. Include itemized deliverables.',
    priority: 'high',
    status: 'todo',
    dueDate: '2026-04-20',
    clientId: 'c4',
    clientName: 'Atlas Ventures',
    tags: ['billing'],
  },
  {
    id: 't3',
    title: 'Design homepage wireframes — NovaMed',
    description: 'Low-fidelity wireframes for the patient portal landing page.',
    priority: 'medium',
    status: 'done',
    dueDate: '2026-04-15',
    clientId: 'c1',
    clientName: 'NovaMed Health',
    tags: ['design', 'wireframe'],
  },
  {
    id: 't4',
    title: 'Follow up with Marcus Webb',
    description: 'Check if they reviewed the proposal. Offer a 30-min call to answer questions.',
    priority: 'medium',
    status: 'todo',
    dueDate: '2026-04-21',
    clientName: 'Harvest Financial',
    tags: ['outreach'],
  },
  {
    id: 't5',
    title: 'Prepare monthly report — Meridian Consulting',
    description: 'Compile metrics, deliverables, and KPIs for April monthly review.',
    priority: 'medium',
    status: 'in_progress',
    dueDate: '2026-04-30',
    clientId: 'c2',
    clientName: 'Meridian Consulting',
    tags: ['reporting'],
  },
  {
    id: 't6',
    title: 'Schedule onboarding call — Kibo Commerce',
    description: 'Send calendar link and onboarding questionnaire to Yuki.',
    priority: 'low',
    status: 'done',
    dueDate: '2026-04-12',
    clientId: 'c5',
    clientName: 'Kibo Commerce',
    tags: ['onboarding'],
  },
  {
    id: 't7',
    title: 'Update brand guidelines — Orion Digital Media',
    description: 'Incorporate client feedback from last review session into the style guide.',
    priority: 'low',
    status: 'todo',
    dueDate: '2026-04-28',
    clientId: 'c3',
    clientName: 'Orion Digital Media',
    tags: ['branding', 'design'],
  },
  {
    id: 't8',
    title: 'Research competitors for GreenLeaf pitch',
    description: 'Analyze top 5 organic brand competitors in the Pacific Northwest market.',
    priority: 'low',
    status: 'todo',
    dueDate: '2026-04-25',
    clientName: 'GreenLeaf Organics',
    tags: ['research', 'proposal'],
  },
]

export const mockRevenueData: RevenueDataPoint[] = [
  { month: 'May', revenue: 18400, target: 20000 },
  { month: 'Jun', revenue: 22100, target: 20000 },
  { month: 'Jul', revenue: 19300, target: 22000 },
  { month: 'Aug', revenue: 25800, target: 22000 },
  { month: 'Sep', revenue: 23600, target: 25000 },
  { month: 'Oct', revenue: 28200, target: 25000 },
  { month: 'Nov', revenue: 31500, target: 28000 },
  { month: 'Dec', revenue: 29800, target: 30000 },
  { month: 'Jan', revenue: 34200, target: 30000 },
  { month: 'Feb', revenue: 38700, target: 35000 },
  { month: 'Mar', revenue: 41100, target: 38000 },
  { month: 'Apr', revenue: 44500, target: 42000 },
]

export const mockLeadSources: LeadSourceDataPoint[] = [
  { name: 'Referral', value: 34, color: '#2563eb' },
  { name: 'LinkedIn', value: 26, color: '#0ea5e9' },
  { name: 'Website', value: 18, color: '#10b981' },
  { name: 'Cold Outreach', value: 13, color: '#f59e0b' },
  { name: 'Other', value: 9, color: '#6b7280' },
]
